[workspace]
members = [
  "crates/rostra-core",
  "crates/rostra-cli",
  "crates/rostra-client",
  "crates/rostra-p2p",
  "crates/rostra-p2p-api"
]
resolver = "2"

[workspace.package]
name = "rostra"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "f2fi, p2p social network"

[workspace.metadata]
name = "rostra"
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.95"
bincode = { version = "2.0.0-rc.3", features = ["derive"] }
blake3 = "1.5.5"
clap = { version = "4.5.23", features = ["derive", "env"] }
convi = { version = "0.1.1" , features = [ "min_target_pointer_width_32" ] }
data-encoding = "2.6"
ed25519-dalek = "2.1.1"
futures = "0.3.31"
iroh-net = { version = "0.28.1", features = ["iroh-relay"] }
itertools = "0.13.0"
pkarr = "2.2.1"
redb-bincode = { version = "0.2.1" }
rostra-core = { path = "crates/rostra-core" }
rostra-client = { path = "crates/rostra-client" }
rostra-p2p = { path = "crates/rostra-p2p" }
rostra-p2p-api = { path = "crates/rostra-p2p-api" }
serde = "1.0.216"
serde_json = "1.0.134"
snafu = { version = "0.8.5", features = ["rust_1_81"] }
tokio = { version = "1.42.0", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[profile.dev]
debug = "line-tables-only"
lto = "off"

[profile.ci]
inherits = "dev"
incremental = false

[profile.release]
debug = "line-tables-only"
lto = "fat"
codegen-units = 1

# Workaround: https://github.com/rust-lang/cargo/issues/12457 which causes
#             https://github.com/ipetkov/crane/issues/370
[profile.dev.build-override]
debug = false
[profile.ci.build-override]
debug = false
[profile.release.build-override]
debug = false
