[package]
name = "rostra-core"

description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[features]
default = []

[dependencies]
bincode = { workspace = true, optional = true }
blake3 = { workspace = true }
data-encoding = { workspace = true }
ed25519-dalek = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
pkarr = { workspace = true, optional = true }
