[package]
name = "rostra-core"

description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[features]
default = []
ed25519-dalek = [ "dep:ed25519-dalek", "dep:rand" ]
serde = [ "dep:serde", "dep:z32", "dep:bip39" ]

[dependencies]
bincode = { workspace = true, optional = true }
bip39 = { workspace = true, optional = true }
blake3 = { workspace = true }
bon = { workspace = true }
convi = { workspace = true }
data-encoding = { workspace = true }
ed25519-dalek = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
pkarr = { workspace = true, optional = true }
z32 = { workspace = true, optional = true }
