[package]
name = "rostra-core"

description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[features]
default = []
pkarr = [ "dep:pkarr" ]

[dependencies]
pkarr = { workspace = true, optional = true }
