[package]
name = "rostra-util-fmt"

description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[features]
default = []

[dependencies]
