[package]
name = "rostra-util-dedup-chan"

description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[features]
default = []

[dependencies]
snafu = { workspace = true }
tokio = { workspace = true }
